default_stages: [pre-commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
    -   id: black
        files: ^odeon/
        args: [--diff]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        files: ^odeon/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
    -   id: mypy
        verbose: true
        files: ^odeon/
        entry: bash -c 'mypy "$@" --install-types --non-interactive || true' --show-traceback

-   repo: https://github.com/PyCQA/isort
    rev: 9.0.1
    hooks:
      - id: isort
        name: Format imports
-   repo: local
    hooks:
    -   id: pytest-check
        stages: [pre-push]
        types: [python]
        name: pytest-check
        entry: python -m pytest -v tests/
        language: system
        pass_filenames: false
        always_run: true
