repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        files: ^cd_ortho/
        args: [--diff]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        verbose: true
        files: ^cd_ortho/
        entry: bash -c 'mypy "$@" || true' --show-traceback

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: Format imports
