name: odeon
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.18.1
  - jsonschema>=3.2.0
  - matplotlib>=3.1.3
  - pytorch>=1.5.0
  - torchvision>=0.5.0
  - tqdm>=4.40.0
  - rasterio==1.1.5
  - fiona>=1.8.13
  - shapely>=1.6.4
  - scikit-learn>=0.23.1
  - scikit-image>=0.16.2
  - pandas>=1.0.0
  - geopandas>=0.9.0
