[tool.flake8]
ignore = "D203"
exclude = [".*", "__pycache__", "docs/source/conf.py"]
max-line-length = 120

[tool.pytest.ini_options]
# log_format = "%(asctime)s, %(levelname)s,  %(funcName)s(), line: %(lineno)d, %(message)s'"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_cli = true
log_level = "INFO"
filterwarnings = ["ignore:.*U.*mode is deprecated:DeprecationWarning"]
