datamodule:
  train_file: /home/dl/speillet/test_odeon_ocsng_32/dataset_ocsng_gers_naf_fold/train_4_fold_2-fold_3-fold_4.csv
  val_file: /home/dl/speillet/test_odeon_ocsng_32/dataset_ocsng_gers_naf_fold/val_4_fold_1.csv
  test_file : /home/dl/speillet/test_odeon_ocsng_32/dataset_ocsng_gers_naf_fold/test_4_fold_5.csv
  resolution: "str"
  deterministic: True
  batch_size: 4
  num_workers: 4
  pin_memory: False
  subset: True

model:
  model_name: unet
  num_classes: 5
  num_channels: 15
  criterion_name: ce
  learning_rate: 0.001
  log_learning_rate: False

trainer:
  files:
    output_folder: /home/dl/speillet/lightning/outputs_lightning/
    name_exp_log: ocsge_test_32
    version_name: version_test
    model_filename: continue_training.ckpt
    model_out_ext: .ckpt
  device:
    device: gpu
    accelerator: str
    num_nodes: 1
    num_processes: 4
    strategy: ddp
    reproducible: False
    progress: 1
  params:
    epochs: 5
    batch_size: 20
    val_check_interval: 0.5
  loggers:
    save_history: True
    get_prediction: False
    save_top_k: 3
    log_histogram: True
    log_graph: True
    log_predictions: True
    log_learning_rate: True
    log_hparams: True
    use_wandb: False
  callbacks:
    early_stopping: True
