from torchmetrics.classification import (BinaryAccuracy, BinaryAUROC,
                                         BinaryAveragePrecision,
                                         BinaryCalibrationError,
                                         BinaryConfusionMatrix, BinaryF1Score,
                                         BinaryJaccardIndex, BinaryPrecision,
                                         BinaryPrecisionRecallCurve,
                                         BinaryRecall,
                                         BinaryRecallAtFixedPrecision,
                                         BinaryROC, BinarySpecificity,
                                         MulticlassAccuracy, MulticlassAUROC,
                                         MulticlassAveragePrecision,
                                         MulticlassCalibrationError,
                                         MulticlassConfusionMatrix,
                                         MulticlassF1Score,
                                         MulticlassJaccardIndex,
                                         MulticlassPrecision,
                                         MulticlassPrecisionRecallCurve,
                                         MulticlassRecall,
                                         MulticlassRecallAtFixedPrecision,
                                         MulticlassROC, MulticlassSpecificity,
                                         MultilabelAccuracy, MultilabelAUROC,
                                         MultilabelAveragePrecision,
                                         MultilabelConfusionMatrix,
                                         MultilabelF1Score,
                                         MultilabelJaccardIndex,
                                         MultilabelPrecision,
                                         MultilabelPrecisionRecallCurve,
                                         MultilabelRecall,
                                         MultilabelRecallAtFixedPrecision,
                                         MultilabelROC, MultilabelSpecificity)

from odeon.core.plugins.plugin import OdnPlugin

from .metric import BINARY_METRIC_REGISTRY, MULTILABEL_METRIC_REGISTRY, MULTICLASS_METRIC_REGISTRY

__all__ = ['binary_metric_plugin', 'multiclass_metric_plugin', 'multilabel_metric_plugin',
           'MULTILABEL_METRIC_REGISTRY', 'MULTICLASS_METRIC_REGISTRY', 'BINARY_METRIC_REGISTRY']

binary_metric_plugin = OdnPlugin(name='binary_metric',
                                 elements={'bin-auc': {'registry': BINARY_METRIC_REGISTRY, 'class': BinaryAUROC},
                                           'bin-accuracy': {'registry': BINARY_METRIC_REGISTRY,
                                                            'class': BinaryAccuracy,
                                                            'aliases': ['bin-acc']},
                                           'bin-specificity': {'registry': BINARY_METRIC_REGISTRY,
                                                               'class': BinarySpecificity,
                                                               'aliases': ['bin-spec']},
                                           'bin-precision': {'registry': BINARY_METRIC_REGISTRY,
                                                             'class': BinaryPrecision,
                                                             'aliases': ['bin-prec']},
                                           'bin-f1score': {'registry': BINARY_METRIC_REGISTRY, 'class': BinaryF1Score,
                                                           'aliases': ['bin-f1']},
                                           'bin-recall': {'registry': BINARY_METRIC_REGISTRY, 'class': BinaryRecall,
                                                          'aliases': ['bin-rec']},
                                           'bin-roc': {'registry': BINARY_METRIC_REGISTRY, 'class': BinaryROC},
                                           'bin-jaccard': {'registry': BINARY_METRIC_REGISTRY,
                                                           'class': BinaryJaccardIndex,
                                                           'aliases': ['bin-jacc', 'bin-iou']},
                                           'bin-confmat': {'registry': BINARY_METRIC_REGISTRY,
                                                           'class': BinaryConfusionMatrix,
                                                           'aliases': ['bin-conf']},
                                           'bin-average-precision': {'registry': BINARY_METRIC_REGISTRY,
                                                                     'class': BinaryAveragePrecision,
                                                                     'aliases': ['bin-aprec']},
                                           'bin-calibration-error': {'registry': BINARY_METRIC_REGISTRY,
                                                                     'class': BinaryCalibrationError,
                                                                     'aliases': ['bin-calib']},
                                           'bin-recall-fixed_precision': {'registry': BINARY_METRIC_REGISTRY,
                                                                          'class': BinaryRecallAtFixedPrecision,
                                                                          'aliases': ['bin-recfix']},
                                           'bin-precision-recall-curve': {'registry': BINARY_METRIC_REGISTRY,
                                                                          'class': BinaryPrecisionRecallCurve,
                                                                          'aliases': ['bin-pr-curve']}
                                           })

multiclass_metric_plugin = OdnPlugin(name='multiclass_metric',
                                     elements={'multic-auc': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                              'class': MulticlassAUROC},
                                               'multic-accuracy': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                   'class': MulticlassAccuracy,
                                                                   'aliases': ['multic-acc']},
                                               'multic-specificity': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                      'class': MulticlassSpecificity,
                                                                      'aliases': ['multic-spec']},
                                               'multic-precision': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                    'class': MulticlassPrecision,
                                                                    'aliases': ['multic-prec']},
                                               'multic-f1score': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                  'class': MulticlassF1Score,
                                                                  'aliases': ['multic-f1']},
                                               'multic-recall': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                 'class': MulticlassRecall,
                                                                 'aliases': ['multic-rec']},
                                               'multic-roc': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                              'class': MulticlassROC},
                                               'multic-jaccard': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                  'class': MulticlassJaccardIndex,
                                                                  'aliases': ['multic-jacc', 'multic-iou']},
                                               'multic-confmat': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                  'class': MulticlassConfusionMatrix,
                                                                  'aliases': ['multic-conf']},
                                               'multic-average-precision': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                            'class': MulticlassAveragePrecision,
                                                                            'aliases': ['multic-aprec']},
                                               'multic-calibration-error': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                            'class': MulticlassCalibrationError,
                                                                            'aliases': ['multic-calib']},
                                               'multic-recall-fixed_precision': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                                 'class':
                                                                                     MulticlassRecallAtFixedPrecision,
                                                                                 'aliases': ['multic-recfix']},
                                               'multic-precision-recall-curve': {'registry': MULTICLASS_METRIC_REGISTRY,
                                                                                 'class':
                                                                                     MulticlassPrecisionRecallCurve,
                                                                                 'aliases': ['multic-pr-curve']}
                                               })

multilabel_metric_plugin = OdnPlugin(name='multilabel_metric',
                                     elements={'multil-auc': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                              'class': MultilabelAUROC},
                                               'multil-accuracy': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                                   'class': MultilabelAccuracy,
                                                                   'aliases': ['multil-acc']},
                                               'multil-specificity': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                                      'class': MultilabelSpecificity,
                                                                      'aliases': ['multil-spec']},
                                               'multil-precision': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                                    'class': MultilabelPrecision,
                                                                    'aliases': ['multil-prec']},
                                               'multil-f1score': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                                  'class': MultilabelF1Score,
                                                                  'aliases': ['multil-f1']},
                                               'multil-recall': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                                 'class': MultilabelRecall,
                                                                 'aliases': ['multil-rec']},
                                               'multil-roc': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                              'class': MultilabelROC},
                                               'multil-jaccard': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                                  'class': MultilabelJaccardIndex,
                                                                  'aliases': ['multil-jacc', 'multil-iou']},
                                               'multil-confmat': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                                  'class': MultilabelConfusionMatrix,
                                                                  'aliases': ['multil-conf']},
                                               'multil-average-precision': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                                            'class': MultilabelAveragePrecision,
                                                                            'aliases': ['multil-aprec']},
                                               'multil-recall-fixed_precision': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                                                 'class':
                                                                                     MultilabelRecallAtFixedPrecision,
                                                                                 'aliases': ['multil-recfix']},
                                               'multil-precision-recall-curve': {'registry': MULTILABEL_METRIC_REGISTRY,
                                                                                 'class':
                                                                                     MultilabelPrecisionRecallCurve,
                                                                                 'aliases': ['multil-pr-curve']}
                                               })
